### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by ghost** [boy0001/FastAsyncRedstone#3]
The plugin is having issues loading on lastest paper 1.10 with latest worldedit, worldguard, FAWE

full server log : http://pastebin.com/Z6eC0f6m
error specific log : http://pastebin.com/MAW5f03T

specific versions:
worldedit: 6.1.3;7a097ca
worldguard: 6.1.2;e38d98d
FAWE: 16.11.11-8995ce2-368-9.11.0
spigot: git-Paper-912 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by boy0001** [comment]
Couldn't replicate.

You should update your WorldEdit btw.
