### ISSUE TITLE
Can not set static final...

### ISSUE THREAD

**Issue by Joannou1** [boy0001/FastAsyncRedstone#6]
Having this odd issue when used in conjunction with ProtocolSupport (Build #620, latest 1.10)
http://hastebin.com/ayexuxulut.css

Using latest builds of WE/WG/FAWE

PaperSpigot: Paper-916 (1.10.2)
FAWE: 16.11.23-091d1ba-376-9.12.0
FARS: 1.0 (16.11.13-f96cb79-9-0.1.4)
WorldEdit: 6.1.5-SNAPSHOT;3645-b0bfa4a
WorldGuard: 6.1.3-SNAPSHOT;1688-c60502f

Removing ProtocolSupport fixes it.
Not sure if you or ProtocolSupport dev can fix this, might as well try here first?

Thanks for making this though, it seems to work great aside from that issue.

**Comment by boy0001** [comment]
Edit: nvm

**Comment by boy0001** [comment]
Enabling before ProtocolSupport fixes it.
